[versions]
androidGradlePlugin = "8.4.1"
kotlin = "1.9.23"
okhttp = "4.12.0"
moshi = "1.15.0"
coroutines = "1.8.1"
androidxCore = "1.12.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
